### ISSUE TITLE
adzone_id修改后返回false

### ISSUE THREAD

**Issue by guocdfeifei** [binhuang2/TaoBaoKeDemo#2]
按照[这个方法](https://www.cnblogs.com/daochong/p/10271533.html)获取的adzoneid 无法使用，请指教

**Comment by binhuang2** [comment]
我这里申请的是app推广位的pid，还需要对应的appkey和app_secret。
adzone_id就是pid下划线分割的最后一串数字

**Comment by guocdfeifei** [comment]
![image](https://user-images.githubusercontent.com/3377194/61213606-142cd380-a738-11e9-9b07-b1338a6509cb.png)

我用这俩网站的都不行，能截个图看看您的推广类型么

**Comment by binhuang2** [comment]
我刚才说了，我申请的是App推广位。

**Comment by guocdfeifei** [comment]
好
